### ISSUE TITLE
Consider publishing to PyPi.org

### ISSUE THREAD

**Issue by mikeholler** [Esterni/pyracing#40]
Hi there,

I love the library! Do you have plans to publish it to PyPi so I can `pip install pyracing`? I can provide guidance if you need help setting it up.

Thanks,

Mike

**Comment by Esterni** [comment]
Hi Mike! Yes, I do plan to publish to PyPi very soon. There's 1 last branch that I'll be merging soon and then I need to figure out the dependencies. Once that's done we'll be able to put it up on PyPi

**Comment by Esterni** [comment]
Hey Mike, we're now published on PyPi. `pip install pyracing` and you'll be set :)

**Comment by mikeholler** [comment]
Thanks @Esterni! I found some other bugs that I'll write up in more detail when I have time, but I appreciate the quick work. One more request for this though, could you please make a git tag on the commit hash that you used to publish to PyPi, and do this whenever you publish? It's invaluable to be able to find which commit a PyPi package comes from, and git tags can help with that.

Otherwise, you might get comments/bug reports for things that have already been fixed in `master`, but not in the PyPi package, for example.

**Comment by Esterni** [comment]
Thanks Mike :) I'm new to this process. I've tagged the appropriate commit version now.

**Comment by mikeholler** [comment]
Hey no problem @Esterni! We all start somewhere :smile: 

I'm a senior software engineer with a focus in Python and Java applications of all kinds. I'm happy to help where I can, especially where it comes to best practices.

For example, I noticed that your git tag is `v0.1.0-beta`. The `-beta` is missing from the PyPi version and may be confusing. Also, it's important to think of git tags as something that, once created, never change. What's more, if you'd like to convey the beta-ness to your users, you can use a pypi version and git tag of `0.1.0b1`. The leading `v` is not required, and it's best if they both match up. You shouldn't name the pypi version `0.1.0-beta` because it goes against the conventions outlined in [PEP 440](https://www.python.org/dev/peps/pep-0440/#pre-releases). Instead, it is better to use `0.1.0b1`. That would make your second beta release `0.1.0b2` and so forth, until you feel like it's good to release and then you can simply publish and tab `0.1.0`. I'm sure this all sounds pedantic, but it really does help developers when libraries adhere to these simple standards.

I'd suggest keeping with the `0.X.Y` version scheme until you feel like the API is relatively stable and you want to ensure backwards compatibility. When you break compatibility between versions, I'd suggest incrementing the `X` version (`0.2.0`).

If you want to read further into versioning schemes, you can take a look here: semver.org

One last thing, it's best to have only one step to remember. Wouldn't it be great if you could run `git tag 0.1.0b2 && git push origin 0.1.0b2` and have a new version automatically show up on PyPi, after being built by an automated system? That's called Continuous Integration and GitHub handles that with [GitHub Actions](https://docs.github.com/en/actions/building-and-testing-code-with-continuous-integration/about-continuous-integration).

If you're interested in talking more, I could spend some time helping you set that up. I'm really excited about this project, and want to see it succeed.

**Comment by Esterni** [comment]
This is all great! If possible, would you mind joining the discord server [mentioned here](https://esterni.github.io/pyracing/contributing/) for more discussion?
