### ISSUE TITLE
Add install_requires block in setup.py to make sure correct dependencies get resolved

### ISSUE THREAD

**Issue by mikeholler** [Esterni/pyracing#41]
I'm using the following command to install pyracing:

```
› pip install -r requirements.txt 
Collecting git+https://github.com/Esterni/pyracing.git@cd25239999f9d1b25705f0272ae5bfbe97f07910 (from -r requirements.txt (line 1))
  Cloning https://github.com/Esterni/pyracing.git (to revision cd25239999f9d1b25705f0272ae5bfbe97f07910) to /tmp/pip-req-build-ufq91ix0
  Running command git clone -q https://github.com/Esterni/pyracing.git /tmp/pip-req-build-ufq91ix0
Building wheels for collected packages: pyracing
  Building wheel for pyracing (setup.py) ... done
  Created wheel for pyracing: filename=pyracing-0.1.0-py3-none-any.whl size=25015 sha256=5bb04c533e242ad0c5726e46b69a38167fbfde1c61b5608474206c3d3e62e9e0
  Stored in directory: /home/mjholler/.cache/pip/wheels/d5/e5/7b/11e8002ae3fcd21e6c5569eaa863a049e529a956b481d3a7de
Successfully built pyracing
Installing collected packages: pyracing
Successfully installed pyracing-0.1.0
```

Once installed, I try to use it like so:

```
(venv) 
iracing-stats/ on master 
› python
Python 3.8.0 (default, Apr 22 2020, 12:03:58) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyracing
>>> from pyracing import client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mjholler/Git/mike.holler/iracing-stats/venv/lib/python3.8/site-packages/pyracing/client.py", line 8, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'
```

You can see that I do not have the proper dependency installed. I could do `pip install httpx=<version>`, but I do not know what the recommended version is, and most python libraries handle this by adding an [`install_requires` block](https://packaging.python.org/discussions/install-requires-vs-requirements/) to `setup.py`.

Here is an example of what that might look like:

```
install_requires=[
    "httpx>=0.13"
]
```

I am only using httpx as an example here because of the error I got. I do not know whether this is comprehensive, or even the correct version. That's why I've not submitted a pull request.

**Comment by Esterni** [comment]
In the meantime, installing the latest version of httpx is what I would recommend. As far as I know, we're using the most recent version of all the modules currently in use with pyracing.

**Comment by Esterni** [comment]
You can also `pip install .` if you have your current directory set to the root folder of the cloned repo. Then when any changes are made you can run `pip install . --upgrade` to ensure tests are using the changes.
