### ISSUE TITLE
Response of GetWorldRecords changed

### ISSUE THREAD

**Issue by NoHeDidnt** [Esterni/pyracing#86]
The endpoint GetWorldRecords returns a different set of numerical keys (and additional values) inside the individual rows. The __init__ method of the WorldRecords class needs to be updated to reflect this change.

- Two attributes have been added: "helmhelmettype" => "9" & "helmfacetype" => "34".

- Most of the old numbers have changed as well, because the numbers assigned to the new attributes were already taken.

**Comment by Esterni** [comment]
Thanks @NoHeDidnt, I pulled a sample query from that endpoint and updated the new key:values
